### ISSUE TITLE
pip install spark-sklearn-(version-no) doesn't work

### ISSUE THREAD

**Issue by falconic** [databricks/spark-sklearn#80]
Hi
I am looking to use best_score_ parameter from GridSearchCV function, but it looks like that is not present in the latest version of the library. When I'm trying to uninstall the latest version and reinstall and older version with the command 
pip install spark-sklearn-(version-no)
It does not work. Please rectify this or refer me to a some documentation to see how I can install older versions in my cluster environments. 
Thanks

**Comment by eliasah** [comment]
That's because it's not the correct command. 

Here is the correct command if you wish to install an older version : 

`pip install spark-sklearn==0.2.0`

Nevertheless, according to the question that you have asked [here](https://stackoverflow.com/questions/50372283/best-score-parameter-from-gridsearchcv-from-spark-sklearn-doesnt-work-with-ver), I wouldn't advise that you solve your problem this way.

If there is a 'bug' in with `best_score`, rather you share a reproducible example so it can be fixed. (Note that v.0.2.0 is almost 2 years old).

**Comment by falconic** [comment]
Thank you for your comment. I see that a bug is already opened for this issue at https://github.com/databricks/spark-sklearn/issues/73. Do you still want me to share a reproducible code for this problem?

**Comment by eliasah** [comment]
Honestly I don't think it's necessary anymore. The problems resides which the scikit dependency lib used by the project which deprecated model_selection.

**Comment by falconic** [comment]
Are there any plans to update that library? Because unless that happens, the scoring and some of the other parameters cannot be used with spark-sklearn library.

**Comment by srowen** [comment]
Yeah, see #73 for more info. I am not sure we can set best_score_
